spring:
  application:
    name: ielts

#database connection
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: ${PORT_SERVER}

#jwt
jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token: ${REFRESH_TOKEN_EXPIRATION}

#logging
logging:
  level:
    root: INFO
    com.ddhva.ielts: DEBUG
    org.springframework: WARN
    org.hibernate.SQL: OFF
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
  file:
    name: logs/ielts.log

dictionary:
  api:
    url: ${API_URL}

scheduler:
  exam:
    enabled: true
    cron: "0 0 3 * * *"
    base-url: https://ielts-up.com
    listening-from: 5
    listening-to: 14
    reading-from: 1
    reading-to: 11