spring:
  application:
    name: ielts
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

#database connection
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      keepalive-time: 60000
      connection-timeout: 30000
      idle-timeout: 1800000
      max-lifetime: 3600000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: ${PORT_SERVER}

#jwt
jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token: ${REFRESH_TOKEN_EXPIRATION}

#logging
logging:
  level:
    root: INFO
    com.ddhva.ielts: DEBUG
    org.springframework: WARN
    org.hibernate.SQL: OFF
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
  file:
    name: logs/ielts.log

dictionary:
  api:
    url: ${API_URL}

crawler:
  base-url: https://study4.com
  tests-path: /tests/ielts/

firebase:
  service-account: ${FIREBASE_KEY_PATH}